version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: web
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
