version: '3.8'

volumes:
  db_data:
  uploads:

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: K(l9h1j-Zmn!f$k
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./webserver/
    container_name: web
    volumes:
      - ./webserver/code/:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: K(l9h1j-Zmn!f$k
    entrypoint: ["/usr/local/bin/wait-for-db.sh", "db", "/var/www/html/configs/updateSQL.php", "/var/www/html/configs/photofoxDB.sql"]