version: '3.8'

volumes:
  db_data:

services:
  web:
    build: ./webserver/
    container_name: web
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: K(l9h1j-Zmn!f$k
    volumes:
      - db_data:/var/lib/mysql